---

- name: Remove Jenkins security auth configure scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/30-configure_roles.groovy"
    state: absent
- name: Remove Jenkins user configure scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/35-configure_users.groovy"
    state: absent
     