---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define jenkins_nexus_url
  set_fact:
    jenkins_nexus_url: "{{ __jenkins_nexus_url }}"
  when: jenkins_nexus_url is not defined

# Install prerequisites
- include: pre_install.yml

# Setup/install tasks.
- include: setup-RedHat-Offline.yml
  when: ansible_os_family == 'RedHat'
  
  # Update Jenkins and install configured plugins.
- include: plugins.yml
  
# FLush any handlers
- include: flush.yml

# Base jenkins configuration
- include: pre_configure.yml

# Any post configuration typically involving plugins
- include: post_configure.yml

# FLush any handlers
- include: flush.yml

# Cleanup
- include: cleanup.yml