---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918

- name: Jenkins plugin installer
  template:
    src: install_plugin.sh
    dest: "{{ jenkins_root }}/scripts"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0755    

- name: Install plugins
  command : "{{jenkins_root}}/scripts/install_plugin.sh {{ item }}"
  args:
    chdir: "{{ jenkins_root }}/scripts"
  with_items: "{{ jenkins_plugins }}"