---
- name: configure vault
  template:
    src: configure_vault.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/10-configure_vault.groovy"
  register: jenkins_vault_config
  when: jenkins_plugin_hashicorp_vault.force == true
  notify: restart jenkins    
  
- name: reset authorization
  template:
    src: configure_roles.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/30-configure_roles.groovy"
  register: jenkins_users_config
  notify: restart jenkins
  when: jenkins_plugin_role_strategy.force  == true
  
- name: reset users
  template:
    src: configure_users.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/35-configure_users.groovy"
  register: jenkins_users_config
  when: jenkins_plugin_role_strategy.force == true
  notify: restart jenkins
  
- name: reset slaves
  template:
    src: configure_slaves.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/40-configure_slaves.groovy"
  register: jenkins_slaves_config
  when: jenkins_plugin_ssh_slaves.force == true
  notify: restart jenkins  

