---

# fail if not redhat
- fail:
    msg: "Non RedHat installations not supported yet" 
  when: ansible_os_family != 'RedHat'

- group: 
    name: "{{ jenkins_group }}"
    state: present
- user: 
    name: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    home: "{{ jenkins_root }}"
    createhome: yes
    generate_ssh_key: yes
#    password: "{{ jenkins_user_password }}"
    
- name: Ensure dependencies are installed.
  package:
    name: 
      - curl
      - libselinux-python
      - unzip
    state: installed
  