---
- group: 
    name: "{{ jenkins_group }}"
    state: present
- user: 
    name: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    home: "{{ jenkins_root }}"
    createhome: yes
    generate_ssh_key: yes
    password: "{{ jenkins_user_password }}"
    
- name: Ensure dependencies are installed.
  package:
    name: 
      - curl
      - libselinux-python
      - unzip
    state: installed
  